### ISSUE TITLE
audience interface could be just did string

### ISSUE THREAD

**Issue by hugomrdias** [ipld/js-dag-ucan#41]
Why do we have an audience interface with `did()` method instead of just a string, which is what we normally have to work with ?

```js
const ucan = await UCAN.issue({
  audience: { did: () => cap.info.originator },
  issuer: ctx.keypair,
  lifetimeInSeconds: 60 * 30,
  capabilities: [
    {
      with: cap.capability.with,
      can: 'identity/register',
    },
  ],
})
```

i end up needing to do something like the above

**Comment by Gozala** [comment]
Library provides `did` module to deal with this
https://github.com/ipld/js-dag-ucan/blob/112ca31646a728287e64e346f5f261e41f44cd35/package.json#L57-L60

The reason it's not simply a string, is because in most applications actors are represented with a reacher data structures. In fact even your code snippet illustrates that. It would be more convenient if `cap.info` had method `did()` so you could just pass it right in. Same goes with keypairs and public keys, instead of having to format them as DIDs library allows you to just add `did()` method on them so you don't have to translate between reacher data structures and string represented DIDs.

I'm open to reconsidering this, but so far I found it to be more convenient than having them as strings (which originally was the case).
